apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-app
spec:
  selector:
    app: influxdb-app
  ports:
    - port: 8086
      protocol: TCP
      name: influxdb
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-clm
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicy: Always
      containers:
      - image: service_influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        livenessProbe:                                        # Permets de verifier le bon fonctionnement du container
          tcpSocket:                                            # tente d'etablir une connexion vers le port specifier si dessous
            port: 8086                                            # socket vers lequel sera effectuer l
          initialDelaySeconds: 15                               # Attends 15 sec avant d'effectuer le premier check
          periodSeconds: 5                                      # Verifie toutes les 5 secondes que la connexion soit toujours valide
        volumeMounts:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: influxdb-vol
          mountPath: /var/lib/influxdb
        env:
          - name: INFLUXDB_CONFIG_PATH
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_config_path
          - name: INFLUXDB_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_admin_user
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_admin_password
      volumes:
      - name: influxdb-vol
        persistentVolumeClaim:
          claimName: influxdb-pv-clm