# Declaration des informations pour la creation du Service
apiVersion: v1
kind: Service                           # Type d'objet
metadata:                               # Données permettant d'identifier l'objet de manière unique
  name: mysql                           # Nom de l'objet
  labels:                                 # Label (Etiquette) de notre objet
    app: mysql-app                              # CLE app VALEUR mysql_app
spec:                                   # Specification de notre service
  type: ClusterIP                         # Type du service
  selector:                               # Les Pods ayant CLE app VALEUR mysql seront expose par le service
    app: mysql-app
  ports:                                  # Port utilise par notre service
    - name: mysql                           # Nom DNS du port
      port: 3306                              # Port utilise
      protocol: TCP                           # Protocole utilise par le port
      targetPort: 3306                        # Flux rediriger sur ce port

---
# Declaration des informations pour la creation du PersitantVolumeClaim
apiVersion: v1                          # Version de l'API
kind: PersistentVolumeClaim             # Type d'objet
metadata:                               # Données permettant d'identifier l'objet de manière unique
  name: mysql-pvc                         # Nom de l'objet
  labels:                                 # LABEL (Etiquette) de l'objet
    app: mysql-app                          # CLE app VALEUR mysql-app 
spec:                                   # Specification du PersitantVolumeClaim
  accessModes:                            # Mode d'acces
  - ReadWriteOnce                         # le volume peut être monté en lecture-écriture par un seul nœud
  resources:                              # Ressources demander par le PVC
    requests:                               # Demande du PVC
      storage: 1Gi                            # Quantite du stockage

---
# Declaration des informations pour la creation du Deployment
apiVersion: apps/v1                     # Version de l'API
kind: Deployment                        # Type d'objet
metadata:                               # Données permettant d'identifier l'objet de manière unique
  name: mysql-deploy                      # Nom de l' objet
  labels:                                 # LABEL (Etiquette) de l'objet
    app: mysql-app                          # CLE app VALEUR mysql-app
spec:                                   # Specification du PersitantVolumeClaim
  replicas: 1                             # Nombre de replicas creer
  selector:                               # Les Pods ayant CLE app VALEUR mysql-app seront utiliser pour les replicas set
    matchLabels:
      app: mysql-app
  strategy:                               # Spécifie la stratégie utilisée pour remplacer les anciens pods par de nouveaux 
    type: Recreate                          # Tous les pods existants sont tués avant que de nouveaux ne soient créés
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      restartPolicy: Always
      containers:
      - image: service_mysql
        imagePullPolicy: Never
        name: mysql
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc