# Détails et spécification du service
apiVersion: v1                                               # Version de API
kind: Service                                                # Quel type d'objet vous voulez créer
metadata:                                                    # Données permettant d'identifier l'objet de manière unique     
  name: nginx-svc                                             # Nom pour identifier le service
  annotations:                                                # Permets d'attacher des métadonnées, récupérable par des outils et bibliothèques. 
    metallb.universe.tf/allow-shared-ip: "ft_services"          # Cle de partage pour colocaliser les services sur la meme IP
spec:                                                       # Quelle spécification vous désirez pour l'objet
  type: LoadBalancer                                          # Type de service
  selector:                                                   # Cle selector pour definir quel pod sera gérer par le service
    app: nginx-deploy                                       # Indique les pods qui le service va exposer (ayant le label "app:nginx")
  ports:                                                    # Liste des ports exposees du services
    - name: http                                              # DNS du port   
      port: 80                                                # Le SERVICE exposee le port 80 dans le cluster
      targetPort: 80                                          # et mappe sur le port 80 du POD 
      protocol: TCP                                           # Protocole de traitement du port
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22

---

# Détails et spécification du déploiement
apiVersion: apps/v1                                         # Version de API apps/v1 est la version qui prend en charge le concept des ReplicaSet
kind: Deployment                                            # Quel type d'objet vous voulez créer 
metadata:                                                   # Données permettant d'identifier l'objet de manière unique
  name: nginx-deploy                                          # Nom pour identifier le déploiement
  labels:                                                     # Etiquette du déploiement
    app: nginx-deploy                                           # CLE=app VALEUR=nginx-deploy
spec:                                                       # Quelle configuration vous désirez pour le ReplicaSet
  replicas: 1                                                 # Nombre de replicas (Nombre de pod identique creer par ce doiploiment)
  selector:                                                   # Cle selector pour definir quel pod sera gérer par le ReplicaSet
    matchLabels:                                                # Condition de correspondance qui consite a repliquer
      app: nginx-deploy                                              # les pods ayant le LABEL app VALEUR nginx
  strategy:                                                   # Spécifie la stratégie utilisée pour remplacer les anciens pods par de nouveaux
    type: Recreate                                              # Tous les pods existants sont tués avant que de nouveaux ne soient créés
  template:                                                   # Gestion par le déploiement des pods respectant ce modèle
    metadata:                                                   # Pods utilisisant les metadatas suivantes
      labels:                                                     # Labels (Étiquette)       
        app: nginx-deploy                                         # CLE=app VALEUR=nginx-deploy
    spec:                                                     # Quelle configuration vous désirez
      containers:                                               #  pour les containers
      - name: nginx                                             # Nom donnée au container
        image: service_nginx                                      # Nom de l'image utilisé
        imagePullPolicy: Never                                    # Forcage de la recuperation de l'image sur le DockerHub