apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:                                       # Specification du deploiment 
  replicas: 1                                 # Nombre de replicas identique creer (POD)
  selector:                                   # CLE selector qui permets de specifier les pods gerer par le deploiments
    matchLabels:                                # qui possede le meme label avec la
      app: phpmyadmin                             # CLE 'app' et VALEUR 'phpmyadmin'
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:                                   # Specification template des pods qui seront generer par le deploiment
    metadata:                                   # Donnee informative relative au pod
      labels:                                     # Etiquette du pod (LABEL)
        app: phpmyadmin                             # CLE 'app' et VALEUR 'phpmyadmin'
    spec:                                       # Specification d'un pods
      containers:                                 # Specification du containeur
      - image: service_phpmyadmin                 # Image docker utiliser pour la creation du pod
        imagePullPolicy: Never                      # Forcage de la recuperation de l'image sur le DockerHub
        name: phpmyadmin                            # Nom donnee au containeur