#Define Alpine Linux as the container's OS
FROM		alpine:latest

#Update server.
RUN			apk update

#Install Nginx.
RUN			apk add nginx

#Install wget.
RUN			apk add wget

#Install php packages (can't say wich does what, too much reading for such little understanding).
RUN 		apk add php7-fpm php7-mcrypt php7-soap \
					php7-openssl php7-gmp php7-pdo_odbc \
					php7-json php7-dom php7-pdo php7-zip \
					php7-mysqli php7-sqlite3 php7-apcu \
					php7-pdo_pgsql php7-bcmath php7-gd \
					php7-odbc php7-pdo_mysql php7-pdo_sqlite \
					php7-gettext php7-xmlreader php7-xmlrpc \
					php7-bz2 php7-iconv php7-pdo_dblib php7-curl \
					php7-ctype

#Download and extract wordpress.
RUN			wget https://www.wordpress.org/latest.tar.gz \
			&& tar -xf latest.tar.gz \
			&& rm -rf latest.tar.gz
RUN 		mv wordpress /var/www/wordpress

#Copy all files from srcs (in the computer) in /root (in the container).
COPY		srcs /root

#Define the directory you will be in when the container boots.
WORKDIR		/root/

#Expose port.
EXPOSE		5050

#Run wordpress_setup.sh when the container boots.
ENTRYPOINT	["sh", "wordpress_setup.sh"]